// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseConfig = {
  user : process.env.DATABASE_USER,
  name : process.env.DATABASE_NAME,
  password : process.env.DATABASE_PASSWORD,
  host : process.env.DATABASE_HOST,
  port : process.env.DATABASE_PORT,
  sslMode: process.env.DATABASE_SSL_MODE,
}

const databaseUrl = `postgresql://${databaseConfig.user}:${databaseConfig.password}@${databaseConfig.host}:${databaseConfig.port}/${databaseConfig.name}?sslmode=${databaseConfig.sslMode}`

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
